---
abstract: 'the JSON Object Model'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
keywords:
  - JSON
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: JSON::JOM
name: JSON-JOM
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  B: 0
  Carp: 0
  Exporter: 0
  JSON: 2.00
  Module::Pluggable: 0
  Object::AUTHORITY: 0
  Scalar::Util: 0
  Tie::Array: 0
  Tie::Hash: 0
  UNIVERSAL::ref: 0.12
  common::sense: 0
  parent: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=JSON-JOM
  homepage: https://metacpan.org/release/JSON-JOM
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-json-jom
version: 0.500
