# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/JSON-JOM/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:test_requires "Test::More 0.61" ;
	:requires "Scalar::Util" , "common::sense" , "parent" ,
		"B", "Carp", "Exporter", "JSON 2.00" , "Module::Pluggable", "Tie::Array", "Tie::Hash",
		"UNIVERSAL::ref 0.12", "Object::AUTHORITY" .

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/JSON/JOM.pm" .

